title: Windows in Detail
author: Fede
email: N/A
url: https://fede718201.github.io/
baseurl: ""
description: >
   In-depth technical analysis of the Windows ecosystem.
permalink: /:slug.html
favicon: "logo.png"
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false
  lowercase_titles: true
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex
jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
